name: flame_nano_rpg
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 0.0.3

environment:
  sdk: ^3.6.0


dependencies:
  flame: ^1.23.0
  flutter:
    sdk: flutter

  meta: any
dev_dependencies:
  very_good_analysis: ^6.0.0

flutter:
  assets:
    - assets/images/
    - assets/images/player/warrior_1/
    - assets/images/player/warrior_2/
    - assets/images/enemies/orc_berserk/
    - assets/images/enemies/orc_shaman/
    - assets/images/enemies/orc_warrior/
    - assets/images/trees/tree/
    - assets/images/objects/mushrooms/
