name: flame_nano_rpg
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 0.0.1

environment:
  sdk: ^3.6.0


dependencies:
  flame: ^1.23.0
  flutter:
    sdk: flutter

dev_dependencies:
  very_good_analysis: ^6.0.0

flutter:
  assets:
    - assets/images/
    - assets/images/player/warrior_1/
    - assets/images/enemies/orc_berserk/
    - assets/images/trees/tree/
