name: flame_nano_rpg
description: "A simple Flame RPG game written in Dart"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 0.0.3

environment:
  sdk: ^3.6.0

dependencies:
  flame: ^1.23.0
  flutter:
    sdk: flutter

  meta: any
dev_dependencies:
  build_runner: 2.4.13
  flutter_gen_runner: 5.8.0
  very_good_analysis: ^6.0.0

flutter:
  assets:
    - assets/images/
    - assets/images/player/warrior_1/
    - assets/images/player/warrior_2/
    - assets/images/enemies/orc_berserk/
    - assets/images/enemies/orc_shaman/
    - assets/images/enemies/orc_warrior/
    - assets/images/trees/tree/
    - assets/images/objects/mushrooms/
flutter_gen:
  integrations:
    flutter_svg: true
